### ISSUE TITLE
check_fen() function returns error if chrome window isn't open

### ISSUE THREAD

**Issue by abdallah1097** [Panc4kes/chess.com-bot#6]
check_fen() function searches for download button, however, if the window isn't open for any reason (One of them is the script requires input from the user, so when the user switches to the terminal the chrome window is closed)

This even prevents the bot to start and operate at all! Which causes the bot to fail totally even though the script is running

The error is as follows:
```bash
$ python main.py
Press any key to continue...
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    board = chess.Board(check_fen())
  File "main.py", line 37, in check_fen
    download.click()
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=87.0.4280.88)

Exception ignored in: <module 'threading' from 'C:\\ProgramData\\Anaconda3\\lib\\threading.py'>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt:

```

Edit: This happens if you start the script and minimize the chrome tab, it'll not start playing at all

**Comment by jsun1590** [comment]
Thanks for the heads up, I'll have a look at your pr :)
